
const BASE_PETS = [
 {id:'chicken',name:'Chicken',icon:'🐔',rarity:'Common',biome:'Forest',income:1,description:'Ein treuer Startbegleiter aus dem Wald.'},
 {id:'dog',name:'Dog',icon:'🐶',rarity:'Common',biome:'Forest',income:2,description:'Freundlich, schnell und immer bereit.'},
 {id:'bird',name:'Bird',icon:'🐦',rarity:'Uncommon',biome:'Forest',income:8,description:'Ein flinker Bewohner der Baumwipfel.'},
 {id:'owl',name:'Burrowing Owl',icon:'🦉',rarity:'Rare',biome:'Forest',income:35,description:'Klug, wachsam und überraschend selten.'},
 {id:'raccoon',name:'Raccoon',icon:'🦝',rarity:'Rare',biome:'Forest',income:45,description:'Der kleine Meisterdieb des Waldes.'},
 {id:'fox',name:'Fox',icon:'🦊',rarity:'Epic',biome:'Forest',income:180,description:'Elegant und unglaublich clever.'},
 {id:'frog',name:'Frog',icon:'🐸',rarity:'Common',biome:'Lake',income:3,description:'Quakt sich direkt in deine Sammlung.'},
 {id:'duck',name:'Duckling',icon:'🐤',rarity:'Common',biome:'Lake',income:5,description:'Klein, gelb und voller Energie.'},
 {id:'catfish',name:'Catfish',icon:'🐟',rarity:'Uncommon',biome:'Lake',income:12,description:'Ein geheimnisvoller Bewohner des Sees.'},
 {id:'turtle',name:'Turtle',icon:'🐢',rarity:'Rare',biome:'Lake',income:60,description:'Langsam unterwegs, stark im Einkommen.'},
 {id:'axolotl',name:'Axolotl',icon:'🪷',rarity:'Legendary',biome:'Lake',income:2400,description:'Eine legendäre und farbenfrohe Erscheinung.'},
 {id:'jerboa',name:'Jerboa',icon:'🐭',rarity:'Common',biome:'Desert',income:6,description:'Springt mühelos durch den heißen Sand.'},
 {id:'camel',name:'Camel',icon:'🐫',rarity:'Rare',biome:'Desert',income:75,description:'Ausdauernder König der Dünen.'},
 {id:'scorpion',name:'Scorpion',icon:'🦂',rarity:'Mythic',biome:'Desert',income:16000,description:'Gefährlich, selten und äußerst wertvoll.'},
 {id:'toucan',name:'Toucan',icon:'🦜',rarity:'Rare',biome:'Jungle',income:110,description:'Bunte Legende aus dem Blätterdach.'},
 {id:'chimp',name:'Chimpanzee',icon:'🐵',rarity:'Rare',biome:'Jungle',income:90,description:'Cleverer Kletterer mit Sammlerinstinkt.'},
 {id:'croc',name:'Crocodile',icon:'🐊',rarity:'Epic',biome:'Jungle',income:420,description:'Ein uralter Jäger im grünen Reich.'},
 {id:'gorilla',name:'Gorilla',icon:'🦍',rarity:'Legendary',biome:'Jungle',income:4800,description:'Legendäre Kraft aus dem Dschungel.'},
 {id:'walrus',name:'Walrus',icon:'🦭',rarity:'Epic',biome:'Snow',income:600,description:'Bleibt selbst im Eis ganz entspannt.'},
 {id:'polar',name:'Polar Bear',icon:'🐻‍❄️',rarity:'Legendary',biome:'Snow',income:7000,description:'Der mächtige Wächter des Schnees.'},
 {id:'mammoth',name:'Mammoth',icon:'🦣',rarity:'Mythic',biome:'Snow',income:42000,description:'Ein gigantischer Schatz aus uralter Zeit.'},
 {id:'lavafrog',name:'Lava Frog',icon:'🌋',rarity:'Epic',biome:'Volcano',income:850,description:'Heißer als jeder andere Frosch.'},
 {id:'bull',name:'Flaming Bull',icon:'🐂',rarity:'Legendary',biome:'Volcano',income:9500,description:'Ein brennender Koloss voller Energie.'},
 {id:'cerberus',name:'Cerberus',icon:'🐺',rarity:'Secret',biome:'Volcano',income:8000000,description:'Das ultimative Geheimnis des Vulkans.'},
 {id:'octopus',name:'Void Octopus',icon:'🐙',rarity:'Cosmic',biome:'Abyss',income:400000,description:'Kosmische Tentakel aus der Tiefe.'},
 {id:'dragon',name:'Rift Dragon',icon:'🐉',rarity:'Secret',biome:'Rift',income:12000000,description:'Eine eigene Demo-Legende aus dem Rift.'}
];
const RARITIES=['Common','Uncommon','Rare','Epic','Legendary','Mythic','Cosmic','Secret'];
const COLORS={Common:'#aab0c0',Uncommon:'#4ade80',Rare:'#38bdf8',Epic:'#c084fc',Legendary:'#fb923c',Mythic:'#f43f8d',Cosmic:'#22d3ee',Secret:'#facc15'};
const BIOMES={Forest:['🌲','#36c989'],Lake:['🌊','#38bdf8'],Desert:['🏜️','#fbbf24'],Jungle:['🌴','#22c55e'],Snow:['❄️','#a5f3fc'],Volcano:['🌋','#fb5d5d'],Abyss:['🌌','#6366f1'],Rift:['⚡','#d946ef']};
const DEFAULT_STATE={owned:{},favorites:[],customPets:[],tasks:[false,false,false],theme:'dark'};
let state=loadState(), currentCollection='owned',onlyMissing=false;
function loadState(){try{return {...DEFAULT_STATE,...JSON.parse(localStorage.getItem('jmEggDexState')||'{}')}}catch{return structuredClone(DEFAULT_STATE)}}
function saveState(message='Gespeichert'){localStorage.setItem('jmEggDexState',JSON.stringify(state));document.querySelector('#lastSave').textContent=new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})+' Uhr';toast(message);renderAll()}
function pets(){return [...BASE_PETS,...state.customPets]}
function fmt(n){return new Intl.NumberFormat('de-DE',{notation:n>=1e6?'compact':'standard',maximumFractionDigits:1}).format(n)}
function pct(n,t){return t?Math.round(n/t*100):0}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.querySelector('#sidebar').classList.remove('open');scrollTo(0,0)}
function petCard(p){const owned=state.owned[p.id]||0,fav=state.favorites.includes(p.id);return `<article class="pet-card" style="--rarity-color:${COLORS[p.rarity]||'#fff'}" data-pet="${p.id}"><div class="pet-top"><span class="rarity" style="color:${COLORS[p.rarity]}">${p.rarity}</span><button class="favorite ${fav?'on':''}" data-fav="${p.id}">⭐</button></div><div class="pet-icon">${p.icon}</div><h3>${p.name}</h3><div class="pet-meta"><span>${BIOMES[p.biome]?.[0]||'✨'} ${p.biome}</span><span class="pet-income">+$${fmt(p.income)}/s</span></div><button class="round-btn ${owned?'on':''}" data-own="${p.id}" title="Gesammelt">${owned?'✓':'+'}</button>${owned>1?` <small>×${owned}</small>`:''}</article>`}
function renderStats(){const ps=pets(),ownedIds=Object.keys(state.owned).filter(id=>state.owned[id]>0),income=ps.reduce((s,p)=>s+(state.owned[p.id]||0)*p.income,0);const rare=ps.filter(p=>state.owned[p.id]).sort((a,b)=>RARITIES.indexOf(b.rarity)-RARITIES.indexOf(a.rarity))[0];document.querySelector('#statsGrid').innerHTML=[['💎',`${ownedIds.length}/${ps.length}`,'Gesammelte Tiere'],['💰',`$${fmt(income)}/s`,'Gesamteinkommen'],['⭐',state.favorites.length,'Favoriten'],['👑',rare?.name||'Noch keines','Seltenstes Tier']].map(x=>`<div class="stat-card glass"><div class="stat-icon">${x[0]}</div><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join('')}
function renderDashboard(){const ps=pets();document.querySelector('#biomeProgress').innerHTML=Object.keys(BIOMES).slice(0,5).map(b=>{const all=ps.filter(p=>p.biome===b),got=all.filter(p=>state.owned[p.id]).length;return `<div class="progress-row"><div class="progress-label"><span>${BIOMES[b][0]} ${b}</span><b>${got}/${all.length}</b></div><div class="progress"><span style="width:${pct(got,all.length)}%"></span></div></div>`}).join('');const p=ps[new Date().getDate()%ps.length];document.querySelector('#dailyPet').innerHTML=`<div class="daily"><div class="daily-icon">${p.icon}</div><div><span class="rarity" style="color:${COLORS[p.rarity]}">${p.rarity}</span><h2>${p.name}</h2><p class="pet-income">+$${fmt(p.income)}/s</p><button class="secondary" data-open="${p.id}">Ansehen</button></div></div>`}
function renderDex(){let list=pets();const q=document.querySelector('#dexSearch').value.toLowerCase(),r=document.querySelector('#rarityFilter').value,b=document.querySelector('#biomeFilter').value,s=document.querySelector('#sortFilter').value;list=list.filter(p=>p.name.toLowerCase().includes(q)&&(r==='all'||p.rarity===r)&&(b==='all'||p.biome===b)&&(!onlyMissing||!state.owned[p.id]));list.sort((a,b)=>s==='income'?b.income-a.income:s==='name'?a.name.localeCompare(b.name):RARITIES.indexOf(b.rarity)-RARITIES.indexOf(a.rarity));document.querySelector('#dexCount').textContent=pets().length;document.querySelector('#petGrid').innerHTML=list.map(petCard).join('')||'<div class="empty">Keine Tiere gefunden.</div>'}
function renderCollection(){const ps=pets();let list=ps.filter(p=>state.owned[p.id]);if(currentCollection==='favorites')list=ps.filter(p=>state.favorites.includes(p.id));if(currentCollection==='duplicates')list=ps.filter(p=>(state.owned[p.id]||0)>1);const income=ps.reduce((s,p)=>s+(state.owned[p.id]||0)*p.income,0),count=ps.filter(p=>state.owned[p.id]).length;document.querySelector('#collectionSummary').innerHTML=`<div class="big-progress" style="--pct:${pct(count,ps.length)}%"><b>${pct(count,ps.length)}%</b></div><div class="summary-data"><div><b>${count}/${ps.length}</b><small>Einträge</small></div><div><b>$${fmt(income)}/s</b><small>Einkommen</small></div><div><b>${Object.values(state.owned).reduce((a,b)=>a+b,0)}</b><small>Tiere gesamt</small></div></div>`;document.querySelector('#collectionGrid').innerHTML=list.map(petCard).join('')||'<div class="empty">Hier ist es noch leer. Öffne den EggDex und sammle dein erstes Tier!</div>'}
function renderBiomes(){const ps=pets();document.querySelector('#biomeGrid').innerHTML=Object.entries(BIOMES).map(([b,[icon,color]])=>{const all=ps.filter(p=>p.biome===b),got=all.filter(p=>state.owned[p.id]).length;return `<article class="biome-card" style="--biome:${color}"><span class="biome-emoji">${icon}</span><span class="eyebrow">BIOM</span><h2>${b}</h2><p>${got} von ${all.length} Tieren gesammelt</p><div class="progress"><span style="width:${pct(got,all.length)}%"></span></div><p><b>${pct(got,all.length)}%</b> abgeschlossen</p></article>`}).join('')}
function renderCalc(){const ps=pets().filter(p=>state.owned[p.id]);document.querySelector('#calcList').innerHTML=ps.length?ps.map(p=>`<div class="calc-row"><span>${p.icon}</span><div><b>${p.name}</b><small class="pet-income"> $${fmt(p.income)}/s</small></div><input class="calc-qty" data-id="${p.id}" type="number" value="${state.owned[p.id]}" min="0"></div>`).join(''):'<div class="empty">Sammle zuerst Tiere im EggDex.</div>';calcResults()}
function calcResults(){const selected=[...document.querySelectorAll('.calc-qty')].map(i=>({p:pets().find(p=>p.id===i.dataset.id),q:+i.value||0})).filter(x=>x.p&&x.q);const total=selected.reduce((s,x)=>s+x.p.income*x.q,0);const top=selected.sort((a,b)=>b.p.income*b.q-a.p.income*a.q).slice(0,5);document.querySelector('#calcResults').innerHTML=`<span class="eyebrow">DEIN ERGEBNIS</span><h2>Gesamteinkommen</h2><div class="money-total">$${fmt(total)}/s</div><div class="result-stack"><div class="result-line"><span>Pro Minute</span><b>$${fmt(total*60)}</b></div><div class="result-line"><span>Pro Stunde</span><b>$${fmt(total*3600)}</b></div><div class="result-line"><span>In 24 Stunden</span><b>$${fmt(total*86400)}</b></div></div><div class="bar-chart">${top.map(x=>`<div style="height:${total?Math.max(6,x.p.income*x.q/Math.max(...top.map(t=>t.p.income*t.q))*100):0}%"><small>${x.p.icon} ${x.p.name}</small></div>`).join('')}</div>`}
function renderCompare(){const ps=pets(),a=ps.find(p=>p.id===document.querySelector('#compareA').value)||ps[0],b=ps.find(p=>p.id===document.querySelector('#compareB').value)||ps[1],win=a.income>=b.income?a.id:b.id;document.querySelector('#compareResult').innerHTML=[a,b].map(p=>`<div class="fighter glass ${p.id===win?'winner':''}">${p.id===win?'<span class="eyebrow">👑 GEWINNER</span>':''}<div class="pet-icon">${p.icon}</div><h2>${p.name}</h2><span class="rarity" style="color:${COLORS[p.rarity]}">${p.rarity}</span><div class="result-stack"><div class="result-line"><span>Einkommen</span><b class="pet-income">$${fmt(p.income)}/s</b></div><div class="result-line"><span>Biom</span><b>${p.biome}</b></div><div class="result-line"><span>Besitz</span><b>${state.owned[p.id]||0}×</b></div></div></div>`).join('')}
function renderTasks(){const tasks=[['🥚','Sammle 5 verschiedene Tiere'],['💰','Erreiche 10.000 $/s'],['⭐','Markiere 3 Favoriten']];document.querySelector('#taskGrid').innerHTML=tasks.map((t,i)=>`<article class="task glass ${state.tasks[i]?'done':''}"><strong>${t[0]}</strong><h3>${t[1]}</h3><p>${state.tasks[i]?'Abgeschlossen! Belohnung gesichert.':'Schließe diese Aufgabe ab und steigere deinen Eventfortschritt.'}</p><button class="${state.tasks[i]?'secondary':'primary'}" data-task="${i}">${state.tasks[i]?'↩ Rückgängig':'Als erledigt markieren'}</button></article>`).join('');const done=state.tasks.filter(Boolean).length;document.querySelector('#eventProgressBar').style.width=pct(done,3)+'%';document.querySelector('#eventProgressText').textContent=`${done} von 3 Aufgaben abgeschlossen`}
function renderCustom(){document.querySelector('#customPets').innerHTML=state.customPets.map(p=>`<div class="custom-row"><span>${p.icon} <b>${p.name}</b><small> · ${p.rarity}</small></span><button class="danger small" data-delete="${p.id}">Löschen</button></div>`).join('')||'<div class="empty">Noch keine eigenen Tiere.</div>'}
function renderAll(){document.body.classList.toggle('light',state.theme==='light');renderStats();renderDashboard();renderDex();renderCollection();renderBiomes();renderCalc();renderCompare();renderTasks();renderCustom()}
function openPet(id){const p=pets().find(p=>p.id===id);if(!p)return;const q=state.owned[id]||0;document.querySelector('#modalContent').innerHTML=`<div class="modal-hero"><div class="pet-icon">${p.icon}</div><span class="rarity" style="color:${COLORS[p.rarity]}">${p.rarity}</span><h1>${p.name}</h1><p>${p.description}</p><div class="result-stack"><div class="result-line"><span>Biom</span><b>${p.biome}</b></div><div class="result-line"><span>Einkommen</span><b class="pet-income">$${fmt(p.income)}/s</b></div></div><div class="quantity"><button data-minus="${id}">−</button><b>${q}× in Sammlung</b><button data-plus="${id}">+</button></div></div>`;document.querySelector('#petModal').classList.add('show')}
function exportData(){const blob=new Blob([JSON.stringify({app:'EggDex by JM Code Studio',version:1,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`eggdex-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup heruntergeladen')}
function init(){
 RARITIES.forEach(r=>{document.querySelector('#rarityFilter').add(new Option(r,r));document.querySelector('#adminRarity').add(new Option(r,r))});Object.keys(BIOMES).forEach(b=>{document.querySelector('#biomeFilter').add(new Option(b,b));document.querySelector('#adminBiome').add(new Option(b,b))});
 const opts=pets().map(p=>`<option value="${p.id}">${p.icon} ${p.name}</option>`).join('');document.querySelector('#compareA').innerHTML=opts;document.querySelector('#compareB').innerHTML=opts;document.querySelector('#compareB').selectedIndex=1;
 document.addEventListener('click',e=>{const b=e.target.closest('button,[data-pet]');if(!b)return;if(b.dataset.page)go(b.dataset.page);if(b.dataset.go)go(b.dataset.go);if(b.dataset.open)openPet(b.dataset.open);if(b.dataset.pet&&!e.target.closest('button'))openPet(b.dataset.pet);if(b.dataset.fav){e.stopPropagation();state.favorites=state.favorites.includes(b.dataset.fav)?state.favorites.filter(x=>x!==b.dataset.fav):[...state.favorites,b.dataset.fav];saveState('Favoriten aktualisiert')}if(b.dataset.own){e.stopPropagation();state.owned[b.dataset.own]=state.owned[b.dataset.own]?0:1;saveState('Sammlung aktualisiert')}if(b.dataset.plus){state.owned[b.dataset.plus]=(state.owned[b.dataset.plus]||0)+1;saveState('Anzahl erhöht');openPet(b.dataset.plus)}if(b.dataset.minus){state.owned[b.dataset.minus]=Math.max(0,(state.owned[b.dataset.minus]||0)-1);saveState('Anzahl verringert');openPet(b.dataset.minus)}if(b.dataset.task!==undefined){state.tasks[+b.dataset.task]=!state.tasks[+b.dataset.task];saveState('Aufgabe aktualisiert')}if(b.dataset.delete){state.customPets=state.customPets.filter(p=>p.id!==b.dataset.delete);delete state.owned[b.dataset.delete];saveState('Eintrag gelöscht')}if(b.hasAttribute('data-close'))document.querySelector('#petModal').classList.remove('show')});
 ['dexSearch','rarityFilter','biomeFilter','sortFilter'].forEach(id=>document.querySelector('#'+id).addEventListener('input',renderDex));document.querySelector('#onlyMissing').onclick=e=>{onlyMissing=!onlyMissing;e.target.classList.toggle('active',onlyMissing);renderDex()};document.querySelectorAll('[data-collection]').forEach(b=>b.onclick=()=>{currentCollection=b.dataset.collection;document.querySelectorAll('[data-collection]').forEach(x=>x.classList.toggle('active',x===b));renderCollection()});document.querySelector('#calcList').addEventListener('input',calcResults);document.querySelector('#compareA').onchange=renderCompare;document.querySelector('#compareB').onchange=renderCompare;document.querySelector('#menuBtn').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';saveState('Design gewechselt')};
 document.querySelector('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){go('eggdex');document.querySelector('#dexSearch').value=e.target.value;renderDex()}});document.querySelector('#petForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.customPets.push({id:'custom-'+Date.now(),name:d.name,icon:d.icon||'🥚',rarity:d.rarity,biome:d.biome,income:+d.income||0,description:d.description||'Ein eigenes Tier von JM Code Studio.'});e.target.reset();saveState('Eigenes Tier hinzugefügt');const opts=pets().map(p=>`<option value="${p.id}">${p.icon} ${p.name}</option>`).join('');document.querySelector('#compareA').innerHTML=opts;document.querySelector('#compareB').innerHTML=opts};
 document.querySelector('#deleteCustomAll').onclick=()=>{if(confirm('Wirklich alle eigenen Tiere löschen?')){state.customPets=[];saveState('Eigene Tiere gelöscht')}};['exportBtn','exportQuick'].forEach(id=>document.querySelector('#'+id).onclick=exportData);document.querySelector('#importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());state={...DEFAULT_STATE,...(data.state||data)};saveState('Backup erfolgreich importiert')}catch{toast('Ungültige Backup-Datei')}};document.querySelector('#resetBtn').onclick=()=>{if(confirm('Achtung: Wirklich ALLE App-Daten löschen?')){state=structuredClone(DEFAULT_STATE);localStorage.removeItem('jmEggDexState');saveState('Alle Daten zurückgesetzt')}};
 renderAll();
}
init();
